project:
  type: website

website:
  title: ""
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: envelope
        aria-label: email
        href: "mailto:jallen108@gsu.edu"
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/joshuallen17
      - icon: github
        aria-label: github
        href: https://github.com/joshuafayallen
format:
  html:
    theme: 
      - allen.scss
    toc: true



