project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.md"

freeze: true
website:
  title: ""
  site-url: "https://joshuafayallen.github.io"
  repo-url: "https://github.com/joshuafayallen/quarto-website"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - text: "Research"
        file: research/index.qmd
      - text: "Teaching"
        file: teaching/index.qmd
      - text: "CV"
        file: CV/index.qmd
      - text: "Blog"
        file: blog/index.qmd
    right:
      - icon: envelope
        aria-label: email
        href: "mailto:jallen108@gsu.edu"
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/joshuallen17
      - icon: github
        aria-label: github
        href: https://github.com/joshuafayallen
format:
  html:
    theme: 
      - allen.scss
    toc: true



